[platformio]
default_envs = stm32g031g8u6-pwlink2

[env:stm32g031g8u6]
platform = ststm32
framework = stm32cube
board = stm32g031g8u6
board_build.ldscript = stm32g031g8u6_app.ld
platform_packages =
  platformio/toolchain-gccarmnoneeabi@^1.140201.0
build_src_filter =
  +<stm32/>
build_flags =
  -D I2C_SLAVE_ADDRESS=0x28
  -D MS4525_PSI_RANGE=1.0f
  -D BARO1_I2C_ADDRESS=0x76
  -D BARO2_I2C_ADDRESS=0x77
  -D BARO_DIFF_SIGN=1
  -D BARO_AUTOZERO=1
  -D DEBUG_LED_ENABLED=1
  -D DEBUG_LED_GPIO_PORT=GPIOA
  -D DEBUG_LED_GPIO_PIN=GPIO_PIN_8
  -Os
upload_protocol = stlink
debug_tool = stlink

[env:stm32g031g8u6-pwlink2]
extends = env:stm32g031g8u6
upload_protocol = cmsis-dap
debug_tool = cmsis-dap

[env:stm32g031g8u6-pwlink2-ledtest]
extends = env:stm32g031g8u6-pwlink2
build_flags =
  ${env:stm32g031g8u6.build_flags}
  -D DEBUG_LED_TEST=1

[env:stm32g031g8u6-pwlink2-gpiotest]
extends = env:stm32g031g8u6-pwlink2
build_flags =
  ${env:stm32g031g8u6.build_flags}
  -D DEBUG_LED_GPIO_TEST=1

[env:stm32g031g8u6-pwlink2-arduino-ledtest]
platform = ststm32
framework = arduino
board = stm32g031g8u6
board_build.f_cpu = 64000000L
platform_packages =
  platformio/toolchain-gccarmnoneeabi@^1.140201.0
build_src_filter =
  +<stm32_arduino_ledtest/>
build_flags =
  -D ARDUINO_GENERIC_G031G8UX
  -D DEBUG_LED_PIN=PA8
lib_deps =
  adafruit/Adafruit NeoPixel@^1.15.1
upload_protocol = cmsis-dap
debug_tool = cmsis-dap
