[platformio]
default_envs = esp32-s3-devkitc-1

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
build_src_filter =
  +<*>
  -<stm32/>
build_flags =
  -D MONITOR_BAUD=115200
  -D I2C_SLAVE_ADDRESS=0x28
  -D I2C_BUS_HZ=100000
  -D MS4525_PSI_RANGE=1.0f
  -D USE_BAROMETERS=1
  -D BARO_I2C_HZ=100000
  -D BARO1_I2C_ADDRESS=0x76
  -D BARO2_I2C_ADDRESS=0x77
  -D BARO_DIFF_SIGN=1
  -D BARO_AUTOZERO=1

[env:esp32-s3-devkitc-1]
board = esp32-s3-devkitc-1
build_unflags =
  -DARDUINO_USB_MODE=1
build_flags =
  ${env.build_flags}
  -D I2C_SDA_PIN=8
  -D I2C_SCL_PIN=9
  -D BARO_I2C_SDA_PIN=4
  -D BARO_I2C_SCL_PIN=5
  -D DEBUG_LED_ENABLED=1
  -D DEBUG_LED_PIN=48
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=0

[env:esp32dev]
board = esp32dev
build_flags =
  ${env.build_flags}
  -D I2C_SDA_PIN=21
  -D I2C_SCL_PIN=22
  -D BARO_I2C_SDA_PIN=4
  -D BARO_I2C_SCL_PIN=5
  -D DEBUG_LED_ENABLED=0

[env:stm32g031g6u6]
platform = ststm32
framework = stm32cube
board = stm32g031g6u6
platform_packages =
  platformio/toolchain-gccarmnoneeabi@^1.140201.0
build_src_filter =
  +<stm32/>
build_flags =
  -D I2C_SLAVE_ADDRESS=0x28
  -D MS4525_PSI_RANGE=1.0f
  -D BARO1_I2C_ADDRESS=0x76
  -D BARO2_I2C_ADDRESS=0x77
  -D BARO_DIFF_SIGN=1
  -D BARO_AUTOZERO=1
  -D DEBUG_LED_ENABLED=1
  -D DEBUG_LED_GPIO_PORT=GPIOA
  -D DEBUG_LED_GPIO_PIN=GPIO_PIN_8
  -Os
upload_protocol = stlink
debug_tool = stlink
